### ISSUE TITLE
Install gcc-10 with offloading support

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/thematrix#21]
I suppose on **all** VMs

**Comment by italoaug** [comment]
I've posted a tutorial to install gcc 10.0.1 with offloading support on Azure  ( https://github.com/devitocodes/devito/wiki/Installing-gcc-10.0.1-with-offloading-support-on-Azure )

**Comment by FabioLuporini** [comment]
Closing because it increases maintenance and we don't have the manpower, currently, for this (and we are clang/aomp/nvc-focussed )
