### ISSUE TITLE
README table improvements

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/thematrix#34]
Markdown tables suck -- you can't have irregular tables. I'd love to make it look like as in the attached image (though feedback welcome)

![IMG_2949](https://user-images.githubusercontent.com/478143/82420277-ced7e180-9a7f-11ea-8f1b-3dbb864a01bb.JPG)

I'd also like to make the font smaller.

I think the way to go is to use HTML, which we can embed in markdown

This is a brainless task, but potentially visually rewarding at the end. To be picked up when one needs something mentally lightweight

**Comment by ggorman** [comment]
Mentally non-taxing? Seems like the ideal task for me!

I think that we should drop this manually maintained table and instead write a script to parse results/benchmarks.json and generate that table automatically. This way it will also be easy to add various href's to the table to bring readers directly to specific results.

**Comment by FabioLuporini** [comment]
yes! it should really be scripted

**Comment by ggorman** [comment]
The basic idea would be:
```python
import pandas as pd

df = pd.read_json("results/benchmarks.json")

# Manipulate df 

df.to_html("fancy_table.html")```

**Comment by FabioLuporini** [comment]
just to be sure:

you don't need the actual performance results for this table. This table is supposed to show what we're running at the moment, what's in our roadmap, and what not

I think the information you would need to scriptify it is available here: https://github.com/devitocodes/thematrix/blob/master/thematrix/thematrix.json

**Comment by ggorman** [comment]
WIP:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>os</th>
      <th>tags</th>
      <th>arch</th>
      <th>cpu</th>
      <th>jobs</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>cpu00-Standard-F64s-v2</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu00]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td>{'1x1-omp': {'platform': 'cpu64', 'num_cpu': '16', 'ram': '64GB', 'num_procs': '1', 'num_threads': '16', 'jit': 'gcc-9', 'language': 'openmp', 'mpi': '0', 'omp_places': 'cores', 'omp_proc_bind': 'close'}, '1x2-omp': {'platform': 'cpu64', 'num_cpu': '32', 'ram': '128GB', 'num_procs': '2', 'num_threads': '16', 'jit': 'gcc-9', 'language': 'openmp', 'mpi': 'basic', 'omp_places': 'cores', 'omp_proc_bind': 'close'}}</td>
    </tr>
    <tr>
      <th>cpu01-Standard-F64s-v2</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu01]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td>{'1x1-omp': {'platform': 'cpu64', 'num_cpu': '16', 'ram': '64GB', 'num_procs': '1', 'num_threads': '16', 'jit': 'gcc-9', 'language': 'openmp', 'mpi': '0', 'omp_places': 'cores', 'omp_proc_bind': 'close'}, '1x2-omp': {'platform': 'cpu64', 'num_cpu': '32', 'ram': '128GB', 'num_procs': '2', 'num_threads': '16', 'jit': 'gcc-9', 'language': 'openmp', 'mpi': 'basic', 'omp_places': 'cores', 'omp_proc_bind': 'close'}}</td>
    </tr>
    <tr>
      <th>cpu03-Standard-H16</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu03]</td>
      <td>x86_64</td>
      <td>HPC-IntelXeonE5-2667</td>
      <td>{'1x1-omp': {'platform': 'cpu64', 'num_cpu': '16', 'ram': '112GB', 'num_procs': '1', 'num_threads': '16', 'jit': 'gcc-9', 'language': 'openmp', 'mpi': '0', 'omp_places': 'cores', 'omp_proc_bind': 'close'}}</td>
    </tr>
    <tr>
      <th>gpu00-Standard-NC6-Promo</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu00]</td>
      <td>kepler</td>
      <td>nonHPC-NVidiaGK210</td>
      <td>{'1x1-omp': {'platform': 'nvidiaX', 'num_cpu': '1', 'ram': '12GB', 'num_procs': '1', 'num_threads': '', 'jit': 'clang', 'language': 'openmp', 'mpi': '0', 'omp_places': '', 'omp_proc_bind': ''}, '1x1-acc': {'platform': 'nvidiaX', 'num_cpu': '1', 'ram': '12GB', 'num_procs': '1', 'num_threads': '', 'jit': 'pgi', 'language': 'openacc', 'mpi': '0', 'omp_places': '', 'omp_proc_bind': ''}}</td>
    </tr>
    <tr>
      <th>gpu01-Standard-NC24-Promo</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu01]</td>
      <td>kepler</td>
      <td>nonHPC-NVidia4xGK210</td>
      <td>{'1x4-mpi-acc': {'platform': 'nvidiaX', 'num_cpu': '1', 'ram': '48GB', 'num_procs': '4', 'num_threads': '', 'jit': 'pgi', 'language': 'openacc', 'mpi': 'basic', 'omp_places': '', 'omp_proc_bind': ''}}</td>
    </tr>
  </tbody>
</table>

**Comment by ggorman** [comment]
WIP

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>os</th>
      <th>tags</th>
      <th>arch</th>
      <th>cpu</th>
      <th>1x1-omp</th>
      <th>1x2-omp</th>
      <th>1x1-acc</th>
      <th>1x4-mpi-acc</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>cpu00-Standard-F64s-v2</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu00]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>64GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>32</td></tr><tr style="text-align: left;"><th>ram</th><td>128GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>2</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th>cpu01-Standard-F64s-v2</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu01]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>64GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>32</td></tr><tr style="text-align: left;"><th>ram</th><td>128GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>2</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th>cpu03-Standard-H16</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu03]</td>
      <td>x86_64</td>
      <td>HPC-IntelXeonE5-2667</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>112GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th>gpu00-Standard-NC6-Promo</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu00]</td>
      <td>kepler</td>
      <td>nonHPC-NVidiaGK210</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>12GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>clang</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>12GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>pgi</td></tr><tr style="text-align: left;"><th>language</th><td>openacc</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th>gpu01-Standard-NC24-Promo</th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu01]</td>
      <td>kepler</td>
      <td>nonHPC-NVidia4xGK210</td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>48GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>4</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>pgi</td></tr><tr style="text-align: left;"><th>language</th><td>openacc</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
    </tr>
  </tbody>
</table>

**Comment by ggorman** [comment]
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>os</th>
      <th>tags</th>
      <th>arch</th>
      <th>cpu</th>
      <th>1x1-omp</th>
      <th>1x2-omp</th>
      <th>1x1-acc</th>
      <th>1x4-mpi-acc</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/fsv2-series">cpu00-Standard-F64s-v2</a></th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu00]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>64GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>32</td></tr><tr style="text-align: left;"><th>ram</th><td>128GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>2</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/fsv2-series">cpu01-Standard-F64s-v2</a></th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu01]</td>
      <td>x86_64</td>
      <td>nonHPC-IntelXeon8168</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>64GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>32</td></tr><tr style="text-align: left;"><th>ram</th><td>128GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>2</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/h-series">cpu03-Standard-H16</a></th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, cpu03]</td>
      <td>x86_64</td>
      <td>HPC-IntelXeonE5-2667</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>cpu64</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>16</td></tr><tr style="text-align: left;"><th>ram</th><td>112GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td>16</td></tr><tr style="text-align: left;"><th>jit</th><td>gcc-9</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td>cores</td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td>close</td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/nc-series">gpu00-Standard-NC6-Promo</a></th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu00]</td>
      <td>kepler</td>
      <td>nonHPC-NVidiaGK210</td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>12GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>clang</td></tr><tr style="text-align: left;"><th>language</th><td>openmp</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>12GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>1</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>pgi</td></tr><tr style="text-align: left;"><th>language</th><td>openacc</td></tr><tr style="text-align: left;"><th>mpi</th><td>0</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
    </tr>
    <tr>
      <th><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/nc-series">gpu01-Standard-NC24-Promo</a></th>
      <td>ubuntu18.04</td>
      <td>[self-hosted, gpu01]</td>
      <td>kepler</td>
      <td>nonHPC-NVidia4xGK210</td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><figure><img src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" alt="x" width=20ch</img></figure></td>
      <td><table border="0" class="dataframe"><tr style="text-align: left;"><th>platform</th><td>nvidiaX</td></tr><tr style="text-align: left;"><th>num_cpu</th><td>1</td></tr><tr style="text-align: left;"><th>ram</th><td>48GB</td></tr><tr style="text-align: left;"><th>num_procs</th><td>4</td></tr><tr style="text-align: left;"><th>num_threads</th><td></td></tr><tr style="text-align: left;"><th>jit</th><td>pgi</td></tr><tr style="text-align: left;"><th>language</th><td>openacc</td></tr><tr style="text-align: left;"><th>mpi</th><td>basic</td></tr><tr style="text-align: left;"><th>omp_places</th><td></td></tr><tr style="text-align: left;"><th>omp_proc_bind</th><td></td></tr></table></td>
    </tr>
  </tbody>
</table>

**Comment by ggorman** [comment]
See https://github.com/devitocodes/thematrix/tree/generate_readme

**Comment by FabioLuporini** [comment]
really nice.

I think we need to think about reorganizing the table as it currently:
* contains some useless and/or redundant information (e.g, tags=[self-hosted runner, ...], platform=cpu64, language=openmp (implicit in the column title e.g. `1x1-omp`) ...)
* `os` and `cpu` column can be squashed in some other columns
* ... and much more. Though I do know this is WIP, I'm just listing ideas

Also, about the beautification. We should try to avoid scroll bars. So in addition to restructuring the table as per above, I'd also decrease the font size and perhaps leave less space in between rows and cols
