### ISSUE TITLE
Must use HPC machines on Azure

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/thematrix#4]

**Comment by ggorman** [comment]
Give me a list of VM families you want access to and I'll request a quota. Here are your options from eastus (region we are currently using for TheMatrix):
Name                                                  CurrentValue    Limit
---------------------------------  --------------  -------
Total Regional vCPUs                                   153             398
Dedicated vCPUs                                              0               0
Total Regional Low-priority vCPUs               0               350
Standard FSv2 Family vCPUs                      128             350
Standard BS Family vCPUs                             1               350
Standard NC Promo Family vCPUs                24              48
Basic A Family vCPUs                                      0               350
Standard A0-A7 Family vCPUs                      0               350
Standard A8-A11 Family vCPUs                     0               350
Standard D Family vCPUs                              0               350
Standard Dv2 Family vCPUs                           0               350
Standard DS Family vCPUs                             0               350
Standard DSv2 Family vCPUs         0               350
Standard G Family vCPUs            0               350
Standard GS Family vCPUs           0               350
Standard F Family vCPUs            0               350
Standard FS Family vCPUs           0               350
Standard NV Family vCPUs           0               48
Standard NC Family vCPUs           0               48
Standard H Family vCPUs            0               8
Standard Av2 Family vCPUs          0               350
Standard LS Family vCPUs           0               350
Standard Dv2 Promo Family vCPUs    0               350
Standard DSv2 Promo Family vCPUs   0               350
Standard MS Family vCPUs           0               0
Standard Dv3 Family vCPUs          0               350
Standard DSv3 Family vCPUs         0               350
Standard Ev3 Family vCPUs          0               350
Standard ESv3 Family vCPUs         0               350
Standard NDS Family vCPUs          0               0
Standard NCSv2 Family vCPUs        0               0
Standard NCSv3 Family vCPUs        0               0
Standard LSv2 Family vCPUs         0               350
Standard PBS Family vCPUs          0               6
Standard EIv3 Family vCPUs         0               350
Standard EISv3 Family vCPUs        0               350
Standard DCS Family vCPUs          0               2
Standard NVSv2 Family vCPUs        0               0
Standard MSv2 Family vCPUs         0               0
Standard HBS Family vCPUs          0               240
Standard HCS Family vCPUs          0               176
Standard NVSv3 Family vCPUs        0               0
Standard NV Promo Family vCPUs     0               48
Standard H Promo Family vCPUs      0               8
Standard DAv4 Family vCPUs         0               0
Standard DASv4 Family vCPUs        0               0
Standard EAv4 Family vCPUs         0               0
Standard EASv4 Family vCPUs        0               0
Standard NDSv3 Family vCPUs        0               0
Standard DCSv2 Family vCPUs        0               0
Standard NVSv4 Family vCPUs        0               0
Standard NDSv2 Family vCPUs        0               0
Standard NPS Family vCPUs          0               0
Standard HBrsv2 Family vCPUs       0               0

Command used: ```az vm list-usage --location "eastus" -o table```

**Comment by FabioLuporini** [comment]
I guess more of a question for @mloubout and/or @rhodrin

**Comment by mloubout** [comment]
F, FS, FSv2 good midrange
Ev3, Esv3, good memory and cpu count, great for gradients
H, definitely a must, IB enabled but fairly small so cheaper to work with.
HBrsv2, HPC AMD fancy one, so yes
HBS, HCS, IB enabled HPC chips so yes

Probably some GPU ones but not sure which ones

**Comment by rhodrin** [comment]
So the main ones we want, but don't currently have access to are the H-series:
H-series
HB-series
HBv2-series
HC-series
(see https://tinyurl.com/y9oasfll for details).

**Comment by FabioLuporini** [comment]
any updates on this front?

**Comment by rhodrin** [comment]
We now have access to the `H16`, `H16m` and `H16mr` (and the equivalent '8' core machines) but that's currently it. No access to the `HB60rs` or `HC44rs` yet.

**Comment by rhodrin** [comment]
So I'll push for again for a `HC44rs` - will try and get a `HB60rs` also but am doubtful about that one.

**Comment by FabioLuporini** [comment]
closing, if it's really an issue we'll find out in many months from now
