### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by rhodrin** [devitocodes/thematrix#8]
We need to:

- Decide where `thematrix.json` lives.
- Create a setup/install.py file that runs the scripts to create the json files required by our workflow.
- When this is done add the execution of this script to our workflow and remove the json files created by this setup script from version control.

**Comment by FabioLuporini** [comment]
* under `path-to-repo/thematrix/thematrix.json
* done, there's now a single `make-` script, called by the first job (`set-runners`) of our GH workflow
* done

closing the issue, but feel free to reopen if you'd like to change something
